---
booktitle: Proceedings of the 30th International Conference on Machine Learning
publisher: PMLR
start: 2013-06-17
end: 2013-06-19
published: 2013-02-13
volume: 28
year: '2013'
shortname: ICML
sections:
- name: cycle-1
  title: Cycle 1 Papers
  published: 2013-02-13
- name: cycle-2
  title: Cycle 2 Papers
  published: 2013-05-13
- name: cycle-3
  title: Cycle 3 Papers
  published: 2013-05-26
layout: proceedings
series: Proceedings of Machine Learning Research
id: ICML-2013
month: 0
abstract: ''
tex_title: 
title: Proceedings of Machine Learning Research
cycles: true
editor:
- given: Sanjoy
  family: Dasgupta
- given: David
  family: McAllester
description: |
  Proceedings of the 30th International Conference on Machine Learning
    Held in Atlanta, Georgia, USA on 17-19 June 2013

  Published in 3 Sections as Volume 28 by the Proceedings of Machine Learning Research.
    Cycle 1 Papers published on 13 February 2013
    Cycle 2 Papers published on 13 May 2013
    Cycle 3 Papers published on 26 May 2013

  Volume Edited by:
    Sanjoy Dasgupta
    David McAllester

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 17--19 Jun
url: http://proceedings.mlr.press
baseurl: "/v28"
twitter_username: mlresearch
github_username: mlresearch
markdown: kramdown
permalink: "/:title.html"
github:
  edit: true
  repository: v28
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
email: ''
conference:
  name: International Conference on Machine Learning
  url: 
  location: Atlanta, Georgia, USA
  dates:
  - 2013-06-17
  - 2013-06-18
  - 2013-06-19
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Auto generated from v28.bib
